[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
This is a decentralized Routes Management Proyect based on Solid and React technologies.Based on a decentralized network,so there is not
a unique central server where all the personal data is stored and classified. All the data is stored in the users' PODS, and each user
knows if the application has access to their data. This proyect aims to :

* Provide the users a Well-formed application.
* Be Reliable, Operable, Functional Suitable and Transferable
* Have different Stakeholders: Users, Developers, SOLID and React Developers...
****

=== Requirements Overview

[role="arc42help"]
****
.Mandatory Requirements
* The system will be based on a decentralized architecture wheredata storage is separated from the app.
* Users can store their routes in their own pods.
* Users can view the routes stored on a map.
* The app will allow a user to share pictures, videos or     information about a route with other friends.
* A user can get notifications when some friend shares a route with him.
* Users can have groups of friends with whom they may want to share a route
* It should be possible to view routes loaded by users that are using a different app, so interoperability with other route management systems should be taken into account.

.Optional Requirements
* The system could work on a mobile device
* Users can share their routes while they are doing the routes

****

=== Quality Goals

[role="arc42help"]
****
The aim of this proyect is to offer the users a way to manage their own routes, following some quality goals in order to guarantee a good user experience.
.Quality Goals Scenarios
[width="100%",cols="4,12",options="header"]
|=========================================================
|Quality Goal |Scenario

|Reliability |
As the storage of the routes is not in a centralized server, the users can have always access to theirs and be able to manage them as the data is always on their PODs.

|Transferability|
The system ensures that the application is compatible with other applications that follow the same system and the users can share their routes or multimedia to other users who have a compatible application.

|Functional Suitability|
Whenever a user performs a change one of his routes or add a new one, the action must be done by the application and save on the record.

|=========================================================
These quality goals are the ones which have the most importance to the major stakeholders on this proyect.

****

=== Stakeholders

[role="arc42help"]
****
.Summary
The following table describes the stakeholders of this project and what is expected from them at the beginning of the project, it will be updated as the project goes on if it is required. 
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _Front-End_ | _Guillermo Fernández-Campoamor Fernández_ | _Focus on the front-end side of the app_
| _Front-End_ | _Fernando Sáenz de Santa María Modroño_ | _Focus on the front-end side of the app_
| _Front-End_ | _Alejandro Matas Sánchez_ | _Focus on the front-end side of the app_
| _Back-End_ | _Andrés García Celis_ | _Focus on the back-end side of the app_
| _Back-End_ | _Clara Miranda García_ | _Focus on the back-end side of the app_
| _Back-End_ | _Violeta Ruiz Martínez_ | _Focus on the back-end side of the app_
| _Back-End_ | _Miguel Rodríguez Huerta_ | _Focus on the back-end side of the app_
|===
