[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
This is a decentralized Routes Management Proyect based on Solid and React technologies.Based on a decentralized network,so there is not
a unique central server where all the personal data is stored and classified. All the data is stored in the users' PODS, and each user
knows if the application has access to their data. This proyect aims to :

* Provide the users a Well-formed application.
* Be Reliable, Operable, Functional Suitable and Transferable
* Have different Stakeholders: Users, Developers, SOLID and React Developers...
****

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[role="arc42help"]
****
The aim of this proyect is to offer the users a way to manage their own routes, following some quality goals in order to guarantee a good user experience.
.Quality Goals Scenarios
[width="100%",cols="4,12",options="header"]
|=========================================================
|Quality Goal |Scenario

|Reliability |
As the storage of the routes is not in a centralized server, the users can have always access to theirs and be able to manage them as the data is always on their PODs.

|Transferability|
The system ensures that the application is compatible with other applications that follow the same system and the users can share their routes or multimedia to other users who have a compatible application.

|Functional Suitability|
Whenever a user performs a change one of his routes or add a new one, the action must be done by the application and save on the record.

|=========================================================
These quality goals are the ones which have the most importance to the major stakeholders on this proyect.

****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
vb