[[section-building-block-view]]

== Building Block View

=== Whitebox Overall System

image:05_BuildingBlocks-Scope and context.svg["Overview diagram"]

Motivation::

The above decomposition eases the development by a fair margin, as the division of tasks is more direct among the development team members; the team has two sub-units, front-end and back-end, and this division clearly states what should be done mostly by each sub-unit, and how they should coordinate to make everything connected. The different modules are created upfront, and from there every member will know what will be connected to what they are creating.

As it can be noted, it is fairly similar to an MVC or a layered architecture.

Contained Building Blocks::
* **Viade**: The main application, the project being created.

Important Interfaces::
* **Pod provider**: Any Pod provider available for the user to choose. Crucial for the application to be able to connect to the user's Pod.
* **User's Pod**: The data storage of the user. The application will have access to it, to move the necessary data to provide its functionalities.
* **User**: The user, which has access to the application, and gives their permission for it to manipulate their Pod, so they can access the functionalities of the application.

==== Level 1 - Viade

image:05_BuildingBlocks-Level 1 - Viade.svg["Structure of the application"]

* **Purpose/Responsibility**: Viade is a route-management system that lets users create routes and share them with their friends, and is based on the _Solid specifications_. It is structured as a layered-architecture web application, with layers connected through facades (very similar to a MVC structure).

* **Contained Building Blocks**:
** **Interface Layer**: The layer with which the user will directly interact. It has all the components related with the user interface, and it relies on the _Control Layer_ to get any needed data to output to the user.
** **Control Layer**: Layer that deals with receiving requests from the _Interface Layer_, do different requests to the _Data Access Layer_, receive the data, save it and send it to the _Interface Layer_.
** **Data Access Layer**: This layer will transform requests from the _Control Layer_ to requests to the User's Pod. In some cases it will retrieve data, and it will process it accordingly so the _Control Layer_ can receive it and use it.

* **Directory/File location**: `viade_en2b/src`.


==== Level 2 - Interface Layer

image:05_BuildingBlocks-Level 2 - Interface.svg["Interface layer structure"]

* **Purpose/Responsibility**: Ease the interaction between the user and the Viade system.

* **Contained Building Blocks**:
** **Module _pages_**: Composed of the principal pages of the system, it contains components from all the other modules.
** **Module _login_**: A small module that contains the necessary code to provide a user with the capability of logging in into the application and enjoy all its functionalities.
** **Module _map_components_**: This module contains the components directly related with the map interface that manage the interactions between the user and the map.
** **Module _generic_components_**: Module contained by components that do not have an specific role and are scattered around the application (like buttons with certain functionality or some interfacecomponents that keep a consistent style troughout the application).
** **Module _spec_components_**: 

* **Directory/File location**: `viade_en2b/src/components`.

==== Level 2 - Control Layer

image:05_BuildingBlocks-Level 2 - Control.svg["Control layer structure"]

* **Purpose/Responsibility**: Validate data and attend requests coming from the interface layer, make requests to the data-access layer to meet those requests and send the response back to the interface layer. In this layer data will also be cached, so the number of petitions to the POD is decreased and thus the application can serve content to the user faster. 

To note: there's only one instance of each cache present in the application, thus these working very much like singletons.

* **Contained Building Blocks**:
** **Module _friendCache_**: Stores and makes petitions related to data of a user's Solid friends.
** **Module _configCache_**: This cache only stores the chosen interface mode (light/dark mode), to pass the state between views. It does not make petitions or receive data from the Data Access Layer, as it does not need to.
** **Module _fileCache_**: Stores and makes petitions related to files that a user has attached to routes. It communicates with the route cache to receive or give information about the files of a route.
** **Module _routeCache_**: Stores and makes petitions regarding routes stored in a user's POD. It communicates with the file cache to receive or give information about the files attached to its routes.

* **Directory/File location**: `viade_en2b/src/caches`.

==== Level 2 - Data Access Layer

image:05_BuildingBlocks-Level 2 - Data.svg["Data access layer structure"]

* **Purpose/Responsibility**: Retrieve and save data from the authenticated user's Pod related to the functionalities of the application. This layer will receive information by the control layer and make use of web standards to move the needed data accordingly.

* **Contained Building Blocks**:
** **Module _gateways_**: As its name says, it contains gateways that bar the passing of data between the control layer and the other submodules in the data access layer; this gateways will redirect the petitions to the correspondent submodules.
** **Module _FileManager_**: Module that interacts with the files the user has attached to the routes in the POD.
** **Module _RouteManager_**: Module that deals with the creation, updating, deletion and listing of routes in the user's POD.
** **Module _FriendManager_**: Module that deals with the Solid friends of the user interacting with the application.


* **Directory/File location**: `viade_en2b/src/data-access`.
