[[section-runtime-view]]
== Runtime View



In this section of the documentation important use cases will be described in order to understand how the system communicates at runtime.

This part of the documentation will be in continuous development.


=== Adding a route

The user will be able to add new routes. The data belonging to that specific route will be stored in its own particular pod.

image:6_addingRoute_Diagram.svg["Adding routes"]

=== Sharing a route

The users are capable of sharing a route that has been previously added with their friends. In order to do it, they will just select the route that should be shared and the system will get it from the user's POD. Afterwards, Viade will notificate the user about the state of the sharing process, indicating whether there's been an error or not.


image:6_sharingRoute_Diagram.svg["Sharing routes"]

=== Adding a friend

In our application, users have the possibility to add other users as friends, and so, to share routes with them.

image:6_addingFriends_Diagram.svg["Adding friends"]


