[[section-deployment-view]]


== Deployment View

.Content
The deployment view describes:

 1. the technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. the mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document the deployment view when your software is executed as distributed system with more then one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture those elements of the infrastructure that are needed to show the deployment of your building blocks. Hardware architects can go beyond that and describe the infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence your system and/or some
cross-cutting concepts. Therefore, you need to know the infrastructure.

.Form

Maybe the highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section you will
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than the deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.

=== Infrastructure Level 1

Describe (usually in a combination of diagrams, tables, and text):

*  the distribution of your system to multiple locations, environments, computers, processors, .. as well as the physical connections between them
*  important justification or motivation for this deployment structure
* Quality and/or performance features of the infrastructure
*  the mapping of software artifacts to elements of the infrastructure

For multiple environments or alternative deployments please copy that section of arc42 for all relevant environments.

_**<Overview Diagram>**_

@startuml

node "Android Phone" as android {
    node "React Native app" as app {
        node "Proprietary code" as owncode
        node "SOLID library" as solidlib
    }
}


node "Web browser (Chrome/Firefox)" as browser {
    node "Web app" as webapp {
        node "Proprietary code" as owncode2
        node "SOLID library" as solidlib2
    }
}

database poddb [
    <b>Pods server</b>
    ----
    This can either be deployed internally,
    or using a free web service.
]

cloud "Maps API" as map



owncode --> solidlib
owncode2 --> solidlib2

solidlib --> poddb : read/write
solidlib2 --> poddb : read

owncode --> map
owncode2 --> map

@enduml

Motivation::

Both Native and Web applications rely on a SOLID library to get data from the pods server/database. Both use, also, the Maps API to show map data, which is then overlaid with a representation of the data collected from the pods.

Quality and/or Performance Features::

_<explanation in text form>_
